---
# tasks file for win_ad_install
  - name: Install AD Domain Services
    win_feature:
            name: AD-Domain-Services
            state: present

  - name: Setup AD controller
    win_domain:
            dns_domain_name: "{{ ad_domain_name }}"
            safe_mode_password: "{{ ansible_password }}"

  - name: Reboot Server
    win_reboot:
  
  - name: List Domain Controllers in domain
    win_shell: "nltest /dclist:{{ ad_domain_name }}"
...
